@baseUrl = http://localhost:5224

###############################################################################
# Schedules Controller Tests
#
# This file tests the /api/schedules/weekly endpoint used by the client Schedule page.
###############################################################################

### 1. Get Weekly Schedule
# Expected: Should return a WeeklyScheduleDto with a dictionary of days and class slots
GET {{baseUrl}}/api/schedules/weekly
Accept: application/json


### 2. Get Schedule by ID
# Expected: Should return a ScheduleDto for the specified ID
GET {{baseUrl}}/api/schedules/C1A2B3C4-1234-5678-9ABC-DEF012345614
Accept: application/json}