global using NUnit.Framework;
global using Microsoft.Playwright;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using System.Text.Json;
global using System.Net;
global using System.Net.Http;
global using StudioScheduler.Shared.Dtos;
